version: 2
updates:
  # API application
  - package-ecosystem: "npm"
    directory: "/src/api"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "xsalazar"
    schedule:
      interval: "daily"

  # Rembg application
  - package-ecosystem: "pip"
    directory: "/src/rembg"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "xsalazar"
    schedule:
      interval: "daily"

  # Combiner application
  - package-ecosystem: "npm"
    directory: "/src/combiner"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "xsalazar"
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "xsalazar"
    schedule:
      interval: "daily"
